function [fi, fix, fiy, fiz, vol] = baseHexCubic(hm,iel,x,y,z)
% computes base functions and derivatives of cubic HEX element in one or several
% points
% hm is the HEX mesh class
% iel is the index
% x, y and z are vector points. Basefunctions are evaluated in these
% points.
%     8-----7
%    /|    /|
%   6-----5 |
%   | 4...|.3
%   |/    |/ 
%   2-----1

iv = hm.Connectivity(iel,:);
I = [1     2     4     3     5     8     6     7];
xc = hm.xnod(iv(I)); yc = hm.ynod(iv(I)); zc = hm.znod(iv(I));

dx = xc(3)-xc(1);
dy = yc(2)-yc(1);
dz = zc(5)-zc(1);
% dx13=xc(3)-xc(1)
% dx24=xc(4)-xc(2)
% dx57=xc(7)-xc(5)
% dx68=xc(8)-xc(6)
% dy12=yc(2)-yc(1)
% dy34=yc(4)-yc(3)
% dy56=yc(6)-yc(5)
% dy78=yc(8)-yc(7)
% dz15=zc(5)-zc(1)
% dz26=zc(6)-zc(2)
% dz37=zc(7)-zc(3)
% dz48=zc(8)-zc(4)

%[nodes,npoints]

psix = [(xc(3)-x)/dx,...
        (xc(4)-x)/dx,...
        (x-xc(1))/dx,...
        (x-xc(2))/dx,...
        (xc(7)-x)/dx,...
        (xc(8)-x)/dx,...
        (x-xc(5))/dx,...
        (x-xc(6))/dx]';
    
psiy = [(yc(2)-y)/dy,...
        (y-yc(1))/dy,...
        (yc(4)-y)/dy,...
        (y-yc(3))/dy,...
        (yc(6)-y)/dy,...
        (y-yc(5))/dy,...
        (yc(8)-y)/dy,...
        (y-yc(7))/dy]';
    
psiz = [(zc(5)-z)/dz,...
        (zc(6)-z)/dz,...
        (zc(7)-z)/dz,...
        (zc(8)-z)/dz,...
        (z-zc(1))/dz,...
        (z-zc(2))/dz,...
        (z-zc(3))/dz,...
        (z-zc(4))/dz]';  
fi = psix.*psiy.*psiz;

%This is all wrong below
x = ones(length(x),1); y = x; z = x;
dpsix = [(xc(3)-x)/dx,...
        (xc(4)-x)/dx,...
        (x-xc(1))/dx,...
        (x-xc(2))/dx,...
        (xc(7)-x)/dx,...
        (xc(8)-x)/dx,...
        (x-xc(5))/dx,...
        (x-xc(6))/dx]';
dpsiy = [(yc(2)-y)/dy,...
        (y-yc(1))/dy,...
        (yc(4)-y)/dy,...
        (y-yc(3))/dy,...
        (yc(6)-y)/dy,...
        (y-yc(5))/dy,...
        (yc(8)-y)/dy,...
        (y-yc(7))/dy]';
dpsiz = [(zc(5)-z)/dz,...
        (zc(6)-z)/dz,...
        (zc(7)-z)/dz,...
        (zc(8)-z)/dz,...
        (z-zc(1))/dz,...
        (z-zc(2))/dz,...
        (z-zc(3))/dz,...
        (z-zc(4))/dz]' ; 
    
fix = dpsix.*psiy.*psiz;
fiy = psix.*dpsiy.*psiz;
fiz = psix.*psiy.*dpsiz;


vol = dx*dy*dz;

